image: maven:3-jdk-8

stages:
  - all

before_script:
  - apt-get update
  - apt-get install -y python python-pip rsync
  - pip install git-fat
  - apt-get install -y sshpass
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan cnode00.vsp.tu-berlin.de >> ~/.ssh/known_hosts
  - sshpass -p 'matsim' git fat pull
#    - sshpass -p 'secret' git fat pull # error: Host key verification failed.

job1:
  stage: all
  script: 
    - mvn install -B --fail-at-end -Dmatsim.preferLocalDtds=true

#-Dmaven.test.redirectTestOutputToFile 

# see http://stackoverflow.com/questions/33430487/how-to-use-gitlab-ci-to-build-a-java-maven-project
