image: maven:3-jdk-8

stages:
  - all

before_script:
  - apt-get update
  - apt-get install -y python python-pip rsync
  - pip install git-fat
  - apt-get install -y sshpass
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan cnode00.vsp.tu-berlin.de >> ~/.ssh/known_hosts
  - sshpass -p 'matsim' git fat pull

job1:
  stage: all
  script:
  - mvn clean test --batch-mode --fail-at-end -Dmatsim.preferLocalDtds=true -Dmaven.test.redirectTestOutputToFile
  # (does not run the *IT tests)

job2:
  stage: all
  script:
  - mvn  failsafe:integration-test failsafe:verify --batch-mode --fail-at-end -Dmatsim.preferLocalDtds=true -Dmaven.test.redirectTestOutputToFile
  # (seems that without the failsafe:verify a failing integration test will not fail the build)


# see http://stackoverflow.com/questions/33430487/how-to-use-gitlab-ci-to-build-a-java-maven-project
