image: maven:3-jdk-8

services:
  - python

stages:
  - prepare
  - build

fat:
  stage: prepare
  script:
    - pip install git-fat
    - git fat pull

job1:
  stage: build
  script: 
    - mvn install -B --fail-at-end -Dmatsim.preferLocalDtds=true

#-Dmaven.test.redirectTestOutputToFile 

# see http://stackoverflow.com/questions/33430487/how-to-use-gitlab-ci-to-build-a-java-maven-project
