image: maven:3-jdk-8

stages:
  - all

before_script:
  script:
    - apt-get update
    - apt-get install -y python
    - apt-get install -y python-pip
    - pip install git-fat
#    - git fat pull # does not work
#    - apt-get install -y sshpass rsync
#    - sshpass -p 'secret' git fat pull # error: Host key verification failed.

job1:
  stage: all
  script: 
    - mvn install -B --fail-at-end -Dmatsim.preferLocalDtds=true

#-Dmaven.test.redirectTestOutputToFile 

# see http://stackoverflow.com/questions/33430487/how-to-use-gitlab-ci-to-build-a-java-maven-project
