/* *********************************************************************** *
 * project: org.matsim.*
 *                                                                         *
 * *********************************************************************** *
 *                                                                         *
 * copyright       : (C) 2008 by the members listed in the COPYING,        *
 *                   LICENSE and WARRANTY file.                            *
 * email           : info at matsim dot org                                *
 *                                                                         *
 * *********************************************************************** *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *   See also COPYING, LICENSE and WARRANTY file                           *
 *                                                                         *
 * *********************************************************************** */

package org.matsim.gui;

import femproto.run.RunMatsim4FloodEvacuation;
import org.matsim.run.gui.Gui;
import org.matsim.run.gui.PopulationSampler;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MATSimGUI {

	public static void main(String[] args) {
		Gui gui = Gui.show("FEM GUI", RunMatsim4FloodEvacuation.class);
		
		// the following material is here to demonstrate that we can, in principle, add menu items.
		// yy maybe we rather want a separate button "FEMTools"?
		
		gui.getToolsMenu().addSeparator();

		JMenu femTools = new JMenu("FEMTools");
		gui.addToMenuBar(femTools);

		JMenuItem mntmCreateSamplePopulation = new JMenuItem("Test");
//		gui.getToolsMenu().add(mntmCreateSamplePopulation);
		femTools.add(mntmCreateSamplePopulation);
		mntmCreateSamplePopulation.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				PopulationSampler popSampler = new PopulationSampler();
				popSampler.setVisible(true);
			}
		});
		
	}

	//	The jar file is generated by "mvn package".  Note that the pom.xml refers at some point to this class here. 

}
